### ISSUE TITLE
Milestone Project 1 - XO  

### ISSUE THREAD

**Issue by kasavine** [someOaks/Algorithms#135]
- [x] def print_board(board):
- [x] def player_input():
- [x] def place_marker(board, marker, position):
- [x] def win_check(board, mark):
- [x] def choose_who_is_first():
- [x] def space_check(board, position):
- [x] def full_board_check(board):
- [x] def player_choice(board):
- [x] def replay():
- [x] main.py - # while loop to keep running the game
