### ISSUE TITLE
Milestone Project 2 - Black Jack

### ISSUE THREAD

**Issue by kasavine** [someOaks/Algorithms#140]
- [x] Card and Deck classes
- [x] Hand and Chip classes
- [ ] Functions -  Game Play
